blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/sfc-gh-cmasterson/Retail-online-store-example-for-migration/discussions
    about: For open-ended questions, please start a Discussion instead of an Issue.
